#!/bin/sh

# Grab the token from parameter 4
token_id=$4;

cd /tmp

if [[ -d "/tmp/Sophos Installer.app" ]]; then
    rm -rf /tmp/Sophos*
fi

# new URL as of Jul 2018
curl -O https://api-cloudstation-us-east-2.prod.hydra.sophos.com/api/download/0cf3735d648c8e382eb6fa7ffce7378c/SophosInstall.zip
unzip SophosInstall.zip

chmod a+x ./Sophos\ Installer.app/Contents/MacOS/Sophos\ Installer
chmod a+x ./Sophos\ Installer.app/Contents/MacOS/tools/com.sophos.bootstrap.helper

# replace the token ID in the downloaded files with the token ID we need to isntall
plutil -replace RegistrationToken -string $token_id ./Sophos\ Installer\ Components/SophosCloudConfig.plist

./Sophos\ Installer.app/Contents/MacOS/Sophos\ Installer --install

exit 0
